<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCTBipTw\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCTBipTw/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCTBipTw.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCTBipTw\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerCTBipTw\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'CTBipTw',
    'container.build_id' => '403de157',
    'container.build_time' => 1550310534,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerCTBipTw');
