<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJsJH2Xu\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJsJH2Xu/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJsJH2Xu.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJsJH2Xu\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerJsJH2Xu\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'JsJH2Xu',
    'container.build_id' => '9580599e',
    'container.build_time' => 1549467193,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerJsJH2Xu');
