<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCy9xlLa\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCy9xlLa/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCy9xlLa.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCy9xlLa\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerCy9xlLa\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'Cy9xlLa',
    'container.build_id' => '5291fcc2',
    'container.build_time' => 1549701716,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerCy9xlLa');
